[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "multi-mod"
version = "0.1.0"
description = "Distribution providing multiple modules"
requires-python = ">=3.8"
